### ISSUE TITLE
🐢[Front-end] small fix of label on the signup checkbox

### ISSUE THREAD

**Issue by OneDeadFox** [maximusDecimalusMeridius/gamerPad#59]

**Comment by maximusDecimalusMeridius** [comment]
Clarify label fix and prioritize with ⭐🚦 *team review*

**Comment by maximusDecimalusMeridius** [comment]
Labels in other files vs. checkbox need to be updated to match uniformity.

**Comment by maximusDecimalusMeridius** [comment]
Reviewed with team decided to leave in until finished product.
